# Copyright 2007-2016 United States Government as represented by the
# Administrator of The National Aeronautics and Space Administration.
# No copyright is claimed in the United States under Title 17, U.S. Code.
# All Rights Reserved.



SRCS   = gm_optimized_msg.cpp
TARGET = gm_optimized_msg

include ../AppMake.mf
