# Copyright 2007-2024 United States Government as represented by the
# Administrator of The National Aeronautics and Space Administration.
# No copyright is claimed in the United States under Title 17, U.S. Code.
# All Rights Reserved.

SRCS   = message_field_iterator.cs
TARGET = $(SRCS:.cs=)

include ../AppMake.mf

