# Copyright 2007-2021 United States Government as represented by the
# Administrator of The National Aeronautics and Space Administration.
# No copyright is claimed in the United States under Title 17, U.S. Code.
# All Rights Reserved.


# Java commands
#
JDK_JAVA_JAVAC  = javac
JDK_JAVA_JAR    = jar
JDK_JAVA_RMIC   = rmic
JDK_JAVA        = java
JDK_JAVA_DOC    = javadoc


# Java stuff
#
JNI_SOURCES_3x  = gov\nasa\gsfc\gmsecapi\jni\*.java

JAVA_SOURCES_3x = gov\nasa\gsfc\gmsecapi\*.java	\
                  gov\nasa\gsfc\gmsecapi\internal\*.java \
                  gov\nasa\gsfc\gmsecapi\mist\*.java \
                  gov\nasa\gsfc\gmsecapi\util\*.java \
                  $(JNI_SOURCES_3x)

JNI_SOURCES_4x  = gov\nasa\gsfc\gmsec\api\jni\*.java \
                  gov\nasa\gsfc\gmsec\api\jni\field\*.java \
                  gov\nasa\gsfc\gmsec\api\jni\mist\*.java \
                  gov\nasa\gsfc\gmsec\api\jni\mist\message\*.java \
                  gov\nasa\gsfc\gmsec\api\jni\util\*.java

JAVA_SOURCES_4x = gov\nasa\gsfc\gmsec\api\*.java	\
                  gov\nasa\gsfc\gmsec\api\field\*.java \
                  gov\nasa\gsfc\gmsec\api\mist\*.java \
                  gov\nasa\gsfc\gmsec\api\mist\message\*.java \
                  gov\nasa\gsfc\gmsec\api\util\*.java \
                  $(JNI_SOURCES_4x)

JAVADOC_3x      = gov.nasa.gsfc.gmsecapi \
                  gov.nasa.gsfc.gmsecapi.mist

JAVADOC_4x      = gov.nasa.gsfc.gmsec.api \
                  gov.nasa.gsfc.gmsec.api.field \
                  gov.nasa.gsfc.gmsec.api.mist  \
                  gov.nasa.gsfc.gmsec.api.mist.message \
                  gov.nasa.gsfc.gmsec.api.util

JAVA_OUTPUT_DIR = classes
JAVA_CLASS_PATH = $(JAVA_OUTPUT_DIR)
JAVADOC_DIR     = docs
JAVA_OPTS       = --release 8


# C++ stuff
#
SRCDIR_3x       = src
SRCDIR_4x       = src_4x


default: version javac_3x javac_4x jar gen-doc


debug: default


version: 
	-$(JDK_JAVA_JAVAC) -version
 

javac_3x: $(JAVA_SOURCES_3x) 
	$(JDK_JAVA_JAVAC) -d $(JAVA_OUTPUT_DIR) -classpath $(JAVA_CLASS_PATH) $(JAVA_OPTS) $?
	$(JDK_JAVA_JAVAC) -h $(SRCDIR_3x) -d $(JAVA_OUTPUT_DIR) -classpath $(JAVA_CLASS_PATH) $(JAVA_OPTS) $(JNI_SOURCES_3x)


javac_4x: $(JAVA_SOURCES_4x) 
	$(JDK_JAVA_JAVAC) -d $(JAVA_OUTPUT_DIR) -classpath $(JAVA_CLASS_PATH) $(JAVA_OPTS) $?
	$(JDK_JAVA_JAVAC) -h $(SRCDIR_4x) -d $(JAVA_OUTPUT_DIR) -classpath $(JAVA_CLASS_PATH) $(JAVA_OPTS) $(JNI_SOURCES_4x)


jar:
	$(JDK_JAVA_JAR) cvf ..\bin\gmsecapi.jar -C $(JAVA_OUTPUT_DIR) gov


clean:
	del /Q $(JAVA_CLASS_PATH)\gov\nasa\gsfc\gmsecapi\*.class
	del /Q $(JAVA_CLASS_PATH)\gov\nasa\gsfc\gmsecapi\jni\*.class
	del /Q $(JAVA_CLASS_PATH)\gov\nasa\gsfc\gmsecapi\mist\*.class
	del /Q $(JAVA_CLASS_PATH)\gov\nasa\gsfc\gmsecapi\util\*.class
	del /Q $(JAVA_CLASS_PATH)\gov\nasa\gsfc\gmsec\api\*.class
	del /Q $(JAVA_CLASS_PATH)\gov\nasa\gsfc\gmsec\api\field\*.class
	del /Q $(JAVA_CLASS_PATH)\gov\nasa\gsfc\gmsec\api\jni\*.class
	del /Q $(JAVA_CLASS_PATH)\gov\nasa\gsfc\gmsec\api\jni\field\*.class
	del /Q $(JAVA_CLASS_PATH)\gov\nasa\gsfc\gmsec\api\jni\mist\*.class
	del /Q $(JAVA_CLASS_PATH)\gov\nasa\gsfc\gmsec\api\jni\util\*.class
	del /Q $(JAVA_CLASS_PATH)\gov\nasa\gsfc\gmsec\api\mist\*.class
	del /Q $(JAVA_CLASS_PATH)\gov\nasa\gsfc\gmsec\api\mist\message\*.class
	del /Q $(JAVA_CLASS_PATH)\gov\nasa\gsfc\gmsec\api\util\*.class
	del /Q $(SRC_3x)\gov_nasa_gsfc_gmsecapi_jni_gmsecJNI.h
	del /Q $(SRC_4x)\gov_nasa_gsfc_gmsec_api_jni_gmsecJNI.h
	del /Q ..\bin\gmsecapi.jar
	del /Q ..\bin\gmsecapi-javadoc.jar


gen-doc:
	-$(JDK_JAVA_DOC) -public -quiet -d $(JAVADOC_DIR) --no-module-directories -sourcepath . $(JAVADOC_4x)
	$(JDK_JAVA_JAR) cf ..\bin\gmsecapi-javadoc.jar $(JAVADOC_DIR)
	$(JDK_JAVA_JAR) uf ..\bin\gmsecapi.jar $(JAVADOC_DIR)
