# Copyright 2007-2016 United States Government as represented by the
# Administrator of The National Aeronautics and Space Administration.
# No copyright is claimed in the United States under Title 17, U.S. Code.
# All Rights Reserved.



SRCS   = gmpub_wsmq_async.c
TARGET = gmpub_wsmq_async_c

include ../AppMake.mf
