# Copyright 2007-2021 United States Government as represented by the
# Administrator of The National Aeronautics and Space Administration.
# No copyright is claimed in the United States under Title 17, U.S. Code.
# All Rights Reserved.


default:
	$(MAKE) -f Make.reply
	$(MAKE) -f Make.request


clean:
	$(MAKE) -f Make.reply $@
	$(MAKE) -f Make.request $@
